app:
   name: SpringBootConfigApp
   description: Welcome to "${app.name}"
    
my:
  greeting: Hello, I have successfuly read the value from prop file
  list.value: One,Two,Three


dbValues:
        "{connectionString:'http://____', userName:'foo', password:'test'}"


db:
   connection: "{connectionString:'http://____', userName:'foo', password:'pass'}"
   host: 127.0.0.1
   port: 1200
   
management.endpoints.web.exposure.include: "*"